/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import Frames.Frame1;
import Panels.Panel1;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author stssio2
 */
public class Panel1 extends javax.swing.JPanel {
    
    /*GridBagLayout layout = new GridBagLayout();
    Panel1 p1;*/
    

    /**
     * Creates new form Panel1
     */
    public Panel1() {
        initComponents();
        //p1 = new Panel1();
        //p1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnPanel2 = new javax.swing.JButton();

        setName(""); // NOI18N

        BtnPanel2.setText("Button");
        BtnPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPanel2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPanel2ActionPerformed
        // TODO add your handling code here:
        Panel1 P = new Panel1();
        P.setVisible(false);
    }//GEN-LAST:event_BtnPanel2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPanel2;
    // End of variables declaration//GEN-END:variables
}
